CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" TEXT NOT NULL CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY,
    "ProductVersion" TEXT NOT NULL
);

BEGIN TRANSACTION;
CREATE TABLE "FLOW_FLOWGRAPH_DESCRIPTION" (
    "ID" INTEGER NOT NULL CONSTRAINT "PK_FLOW_FLOWGRAPH_DESCRIPTION" PRIMARY KEY AUTOINCREMENT,
    "NAME" TEXT NOT NULL,
    "DESCRIPTION" TEXT NOT NULL,
    "JSON_SERIALIZED_FLOW" TEXT NOT NULL
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260818093638_InitialCreate', '10.0.11');

COMMIT;

