// <auto-generated />
using FlowStateBlazor.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlowStateBlazor.Data.Migrations.SqliteMigrations
{
    [DbContext(typeof(FlowStateSqliteContext))]
    [Migration("20260818093638_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("FlowStateBlazor.Data.Models.FlowGraphDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("JsonFlowSerialized")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("JSON_SERIALIZED_FLOW");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.ToTable("FLOW_FLOWGRAPH_DESCRIPTION", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
