// <auto-generated />
using FlowStateBlazor.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace FlowStateBlazor.Data.Migrations.OracleMigrations
{
    [DbContext(typeof(FlowStateOracleContext))]
    [Migration("20260818093559_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlowStateBlazor.Data.Models.FlowGraphDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("JsonFlowSerialized")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("JSON_SERIALIZED_FLOW");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.ToTable("FLOW_FLOWGRAPH_DESCRIPTION", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
